id: P80A3B85E
initial_creation_type: ocr
source_metadata:
  volumes:
    fb3ac81327f24fe78bda9c86801b68a6:
      base_file: v057.txt
      image_group_id: I1PD95902
      title: དབུ་མ་རིན་པོ་ཆེའི་སྒྲོན་མ།
      total_pages: 1605
      volume_number: 57
